# https://docs.docker.com/compose/compose-file/#/versioning
version: '3.8'

services:
  nginx:
    # https://hub.docker.com/_/nginx
    container_name: wandersnap_nginx
    platform: linux/arm64
    build: ./nginx
    depends_on:
      - api
      - admin
    volumes:
      - ${WANDERSNAP_ADMIN_CODEBASE}:/var/www/vhost/admin:cached
      - ${WANDERSNAP_API_CODEBASE}:/var/www/vhost/api:cached
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/etc/nginx/ssl/
    working_dir: /var/www/vhost/
    ports:
      - '80:80'
      - '443:443'
    networks:
      wandersnap_network:
        aliases:
          - wandersnap-api.test
          - wandersnap-admin.test


  api:
    # https://hub.docker.com/_/php
    container_name: wandersnap_api
    platform: linux/arm64
    build: ./php
    environment:
      PHP_MEMORY_LIMIT: '256M'
      COMPOSER_MEMORY_LIMIT: '-1'
    volumes:
      - ${WANDERSNAP_API_CODEBASE}:/var/www/vhost/api:cached
    working_dir: /var/www/vhost/api
    ports:
      - '9000:9000'
    networks:
      - wandersnap_network

  admin:
    # https://hub.docker.com/_/php
    container_name: wandersnap_admin
    build: ./php
    environment:
      PHP_MEMORY_LIMIT: '256M'
      COMPOSER_MEMORY_LIMIT: '-1'
    volumes:
      - ${WANDERSNAP_ADMIN_CODEBASE}:/var/www/vhost/admin:cached
    working_dir: /var/www/vhost/admin
    ports:
      - '9001:9000'
    networks:
      - wandersnap_network

  mysql:
    # https://hub.docker.com/r/mysql/mysql-server/
    container_name: wandersnap_mysql
    image: mysql/mysql-server:latest
    platform: linux/arm64
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'wandersnap_api'
      MYSQL_USER: 'wandersnap_api'
      MYSQL_PASSWORD: 'wandersnap_api'
      MYSQL_ROOT_HOST: '%'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - wandersnap_network
    ports:
      - "4406:3306"

  redis:
    image: redis:6.2.5
    container_name: wandersnap_redis
    platform: linux/arm64
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data
    restart: always
    networks:
      - wandersnap_network

  mailpit:
    image: axllent/mailpit
    platform: linux/arm64
    container_name: wandersnap_mailpit
    networks:
      - wandersnap_network
    ports:
      - "1025:1025"
      - "8025:8025"

  horizon:
    container_name: wandersnap_horizon
    image: wandersnap-horizon
    build:
      context: ./php
    working_dir: /var/www/vhost/
    user: "www-data:www-data"
    networks:
      - wandersnap_network
    environment:
      PHP_MEMORY_LIMIT: '128M'
      COMPOSER_MEMORY_LIMIT: '-1'
      QUEUE_CONNECTION: 'redis'
      REDIS_HOST: 'redis'
    depends_on:
      - redis
    volumes:
      - ${WANDERSNAP_ADMIN_CODEBASE}:/var/www/vhost/admin:cached
      - ${WANDERSNAP_API_CODEBASE}:/var/www/vhost/api:cached
      - ./php/worker:/etc/supervisor/conf.d
      - ./php/local/supervisord/logs:/etc/supervisor/logs
      - ./php/local/supervisord/pid:/etc/supervisor/pid
      - ./php/local/supervisord/logs/horizon_worker.log:/var/www/vhost/dannewns.co.uk/storage/logs/horizon_worker.log
    command: [ "/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/horizon.conf", "-u", "www-data", "-l", "/etc/supervisor/logs/supervisord.log", "-j", "/etc/supervisor/pid/supervisord.pid" ]

volumes:
  wandersnap_network-mysql-data-volume:

networks:
  wandersnap_network:
    driver: bridge
